# Generated by Django 6.0.7 on 2026-07-26 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='clientes_fotos/')),
                ('status', models.CharField(default='Ativo', max_length=100)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('visivel_cliente', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastas', to='gestao.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('visivel_cliente', models.BooleanField(default=False)),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='gestao.pasta')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('REALIZAR', 'Realizar'), ('REALIZANDO', 'Realizando'), ('REALIZADO', 'Feito')], default='REALIZAR', max_length=20)),
                ('progresso', models.IntegerField(default=0)),
                ('prazo', models.DateField()),
                ('categoria', models.CharField(max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='gestao.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='VersaoArquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_versao', models.IntegerField()),
                ('arquivo_fisico', models.FileField(upload_to='arquivos_projetos/')),
                ('mensagem_commit', models.CharField(max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='gestao.arquivo')),
            ],
        ),
    ]
