# Generated by Django 6.0.7 on 2026-08-17 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_tarefa_categoria_tarefa_prazo_alter_tarefa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='projeto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos_soltos', to='gestao.projeto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='gestao.pasta'),
        ),
    ]
