# Generated by Django 6.0.7 on 2026-08-24 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_arquivo_projeto_alter_arquivo_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arquivos', to='gestao.tarefa'),
        ),
    ]
