# Generated by Django 6.0.7 on 2026-07-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0003_cliente_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='arquivado',
            field=models.BooleanField(default=False),
        ),
    ]
