# Generated by Django 6.0.7 on 2026-08-27 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0004_arquivo_tarefa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='tamanho_bytes',
        ),
        migrations.AddField(
            model_name='arquivo',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arquivo',
            name='versao_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versoes', to='gestao.arquivo'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arquivos', to='gestao.projeto'),
        ),
        migrations.AlterField(
            model_name='arquivo',
            name='tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestao.tarefa'),
        ),
    ]
