# Generated by Django 6.0.7 on 2026-08-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0005_remove_arquivo_tamanho_bytes_arquivo_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='tamanho_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
