# Generated by Django 6.0.7 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0006_arquivo_tamanho_bytes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="arquivado",
            field=models.BooleanField(default=False),
        ),
    ]
