# Generated by Django 6.0.7 on 2026-09-06 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0007_tarefa_arquivado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(default='WIP', max_length=50),
        ),
    ]
