# Generated by Django 6.0.7 on 2026-09-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestao", "0008_alter_tarefa_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="prioridade",
            field=models.CharField(default="normal", max_length=20),
        ),
    ]
