# Generated by Django 6.0.7 on 2026-09-06 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0009_tarefa_prioridade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data', models.DateField()),
                ('horario', models.TimeField(blank=True, null=True)),
                ('duracao_minutos', models.IntegerField(default=60)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='gestao.projeto')),
            ],
        ),
    ]
