# Generated by Django 6.0.7 on 2026-09-08 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0010_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='visivel_cliente',
            field=models.BooleanField(default=False),
        ),
    ]
