# Generated by Django 6.0.7 on 2026-09-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0011_arquivo_visivel_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasta',
            name='visivel_cliente',
            field=models.BooleanField(default=False),
        ),
    ]
