# Generated by Django 6.0.7 on 2026-09-08 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0012_pasta_visivel_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_acesso',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
