# Generated by Django 6.0.7 on 2026-09-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0013_cliente_codigo_acesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='deletado',
            field=models.BooleanField(default=False),
        ),
    ]
