# Generated by Django 6.0.7 on 2026-09-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0014_cliente_deletado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
