# Generated by Django 6.0.7 on 2026-10-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0016_arquivo_status_aprovacao_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoValidacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('codigo', models.CharField(max_length=6)),
                ('tipo', models.CharField(choices=[('CADASTRO', 'Cadastro'), ('RECUPERACAO', 'Recuperação')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
