# Generated by Django 6.0.7 on 2026-10-04 04:26

import gestao.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0018_cliente_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivo',
            name='arquivo',
            field=models.FileField(upload_to='projetos_arquivos/', validators=[gestao.models.validar_arquivo_seguro]),
        ),
    ]
